### ISSUE TITLE
Incorrect module-info.java

### ISSUE THREAD

**Issue by Amndeep7** [RalleYTN/XInput-Plugin-for-JInput#1]
Hello, trying to use your library via maven (via jitpack).  However, its build on jitpack is failing I believe primarily due to issues with module-info.java.  [Here](https://jitpack.io/com/github/RalleYTN/XInput-Plugin-for-JInput/1.1.0/build.log) is the full jitpack log; what follows below is the error section from that log:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XIControllerTestFrame.java:[26,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XIControllerTestFrame.java:[27,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/CheckList.java:[29,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/CheckList.java:[30,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/CheckList.java:[31,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/CheckList.java:[32,13] package javax.swing is not visible
  (package javax.swing is declared in module java.desktop, but module de.ralleytn.plugins.jinput.xinput does not read it)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XIControllerTestFrame.java:[61,21] cannot find symbol
  symbol: method pack()
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XIControllerTestFrame.java:[62,21] cannot find symbol
  symbol: method setLocationRelativeTo(<nulltype>)
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XInputPluginTest.java:[111,22] cannot find symbol
  symbol:   method setVisible(boolean)
  location: variable frame of type de.ralleytn.plugins.jinput.xinput.tests.XIControllerTestFrame
[ERROR] /home/jitpack/build/src/test/java/de/ralleytn/plugins/jinput/xinput/tests/XInputPluginTest.java:[204,22] cannot find symbol
  symbol:   method dispose()
  location: variable frame of type de.ralleytn.plugins.jinput.xinput.tests.XIControllerTestFrame
[INFO] 10 errors 
```

Version 1.0.0 works just fine - so I think the primary issue is just this module-info.java file.

**Comment by RalleYTN** [comment]
I'll look into it

**Comment by RalleYTN** [comment]
You are trying to build the unit tests with it. Is it not possible to skip the unit tests?

**Comment by Amndeep7** [comment]
I dunno - you're gonna have to talk with the jitpack folks about that haha.  

Presumably if I pull your library down manually, and then choose to not run the unit tests, it'll work fine.  But I'd like to use jitpack to download your library as part of the maven build process.  However, jitpack is having the above issue with your library, which I think is most probably an error with how the module-info.java file is set up.  I'd offer to fix it cause I don't think it's crazy complicated, but I haven't touched Java 9's new module stuff yet.

**Comment by RalleYTN** [comment]
I just have to require java.desktop in the module-info.java but I dont really want to do it since the actual library doesnt use any of its classes, only the unit tests do.... I will probably make a Java 8 branch for Jitpack users.

**Comment by RalleYTN** [comment]
Ok I created a new branch and its passing the build. Try running Jitpack with this as version number: dc6be64.

**Comment by Amndeep7** [comment]
The Maven/Jitpack combo worked!  For reference, [here's the jitpack log](https://jitpack.io/com/github/RalleYTN/XInput-Plugin-for-JInput/dc6be64/build.log) for the build/commit that you told me to use.  When I told Maven to download the dependencies by building the project in Eclilpse, it downloaded that branch and then the project ran correctly.  

In the future, I should presumably be using the "java8" branch, but are you also gonna have official releases from there, or will I always just be using the latest commit?

**Comment by RalleYTN** [comment]
This library is pretty much complete. If Microsoft doesn't come along with new functions in their XInput library and the JInput library doesn't get any significant updates that require me to touch this library, I will not update it. Exception from this rule are bug fixes of course.
But yeah. The Java 8 branch will not get actual releases so if I put a new version up you have to use the commit ID.

**Comment by Amndeep7** [comment]
Got it, thanks!
